import 'package:flutter/material.dart';

// Map<int, String> expertiseMapping = {
//   1: "Emergency Services",
//   2: "Refund Services",
//   3: "Railway Security Force",
//   4: "Disaster Response",
//   5: "Warning and Forecast Services",
//   6: "Relay Weather Data",
//   7: "Forecast ",
//   8: "Warning Force",
//   9: "Disaster management Team",
//   10: "Civil Service",
//   11: "Technical Response Team",
//   12: "Disaster Training Team",
//   13: "Food security",
// };

// Map<int, IconData> agencyLogo = {
//   1: Icons.help_outline_sharp,
//   2: Icons.price_check_rounded,
//   3: Icons.train,
//   4: Icons.escalator_warning_rounded,
//   5: Icons.warning_rounded,
//   6: Icons.cloud,
//   7: Icons.ac_unit_outlined,
//   8: Icons.wrong_location_outlined,
//   9: Icons.manage_accounts,
//   10: Icons.group,
//   11: Icons.code,
//   12: Icons.school,
//   13: Icons.food_bank,
// };

// final List<String> agencyKeys = [
//   'NDMA',
//   'NDRF',
//   'MHA',
//   'DMD',
//   'MoD',
//   'DRDO',
//   'MoHFW',
//   'NIDM',
//   'MoCA',
//   'DGCA',
//   'AAI',
//   'MoP',
//   'NDMRC',
//   'MIB',
//   'FCI',
//   'NAFED',
//   'CCSF',
//   'MoES',
//   'GSI',
//   'IMD',
//   'NWFC',
//   'CWD',
//   'TNRMC',
//   'DRMC',
//   'MRMC',
//   'KRMC',
//   'KLRMC',
//   'PRMC',
//   'NRMC',
//   'VRMC',
//   'TNNIC',
//   'APNIC',
//   'KLNIC',
//   'MHNIC',
//   'KTNIC',
//   'INCOIS',
//   'IOFS',
//   'INDIS',
//   'IOTEWS',
//   'NCCR',
//   'NCMC',
//   'TNSDMA',
//   'TNSEOC',
//   'TNSDRF',
//   'DRT',
//   'TN SDMF',
//   'MDDMA',
//   'RPF',
//   'CDF',
//   'KDDMA',
//   'CDDMA',
//   'TDDMA',
//   'ADDMA',
//   'CDDDMA',
//   'DDDMA',
//   'VDDMA',
//   'VlDDMA',
//   'VELDDMA',
//   'TEDDMA',
//   'TPDMA',
//   'TIPDMA',
//   'THPDMA',
//   'SPDMA',
//   'SAPDDMA',
//   'RAPDDMA',
//   'PDDMA',
//   'PMDDMA',
//   'NDDMA',
//   'DGDDMA',
//   'NGCDDMA',
//   'NKDDMA',
//   'NGDDMA',
//   'KADDMA',
//   'KCDDMA',
//   'EDDMA',
//   'KUDDMA',
//   'PUDDMA',
//   'TTDDMA',
//   'APDDMA',
//   'ERDDMA',
//   'IDDDMA',
//   'KSDDMA',
//   'KTDDMA',
//   'MLSDMA',
//   'KKSDMA',
//   'PLSDMA',
//   'PMSDMA',
//   'THSDMA',
//   'TRSDMA',
//   'THRSDMA',
//   'MSDMA',
//   'PNDDMA',
//   'NSDDMA',
//   'AGBDDMA',
//   'NDDDMA',
//   'DLDDMA',
//   'JGDDMA',
//   'BDDDMA',
//   'WDDMA',
//   'AKDMA',
//   'AMDDMA',
//   'YTDDMA',
//   'WRDDMA',
//   'NGPDDMA',
//   'BHDDMA',
//   'GDDMA',
//   'UKHSDMA',
//   'DHSDMA',
//   'UKSDMA',
//   'DHRSDMA',
//   'HSDMA',
//   'MKDDMA',
//   'MGDDMA',
//   'MDKDDMA',
//   'HSDDMA',
//   'MYDDMA',
//   'MDYDDMA',
//   'DVDDMA',
//   'CHDDMA',
//   'DHDDMA',
//   'TKDDMA',
//   'BGDDMA',
//   'CRDDMA',
//   'KLDDMA',
//   'DVHDDMA',
//   'KSDMA'
// ];

// Future<void> populateDataBase() async {
//   for (String key in agencyKeys) {
//     Map<dynamic, dynamic> curData = agencyList[key] ?? {};
//     String agencyName = curData["agencyName"];
//     String agencyKey = key;
//     String agencyLogo = curData["agencyLogo"];
//     int agencyType = curData["agencyType"];
//     String agencyOperatingState = curData["OperatingState"];
//     String agencyOperatingLocation = curData["operatingLocation"] ?? "";
//     List agencyChildAgencies = curData["childAgencies"];
//     double agencyLat = curData["agencyLat"] ?? 0.0;
//     double agencyLong = curData["agencyLong"] ?? 0.0;
//     Map<String, dynamic> dbEntry = {
//       'agencyName': agencyName,
//       'agencyKey': agencyKey,
//       'agencyLogo': agencyLogo,
//       'agencyType': agencyType,
//       'agencyOperatingState': agencyOperatingState,
//       'agencyOperatingLocation': agencyOperatingLocation,
//       'agencyLatitutude': agencyLat,
//       'agencyLongitude': agencyLong,
//       'agencyAssociates': agencyChildAgencies,
//       'agencyEmployee': []
//     };
//   }
//   print("Operation Succesfull");
// }
