// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0l3cDIL4hZeipBPLFBCleGlVgbhOqAM',
    appId: '1:888561835044:web:ec6c7a15271c84d3924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    authDomain: 'sih-23.firebaseapp.com',
    storageBucket: 'sih-23.appspot.com',
    measurementId: 'G-6CHCE0DY8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI81Yy74GDrQShLhYkOHTn3jhjMh2nGY8',
    appId: '1:888561835044:android:508c536997f7ecc0924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    storageBucket: 'sih-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC14ean1YYS-0IV0VzkPZS4cbYGm5TLhzI',
    appId: '1:888561835044:ios:643540ddb4283926924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    storageBucket: 'sih-23.appspot.com',
    iosClientId: '888561835044-s3s5i75lhpesh7ickpr1mridre4ml80j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC14ean1YYS-0IV0VzkPZS4cbYGm5TLhzI',
    appId: '1:888561835044:ios:c3b04bd5c17d0a75924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    storageBucket: 'sih-23.appspot.com',
    iosClientId: '888561835044-0i0komtfddqudr713p5busacdl5h92uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih2023.RunnerTests',
  );
}
